### PR TITLE
extracted zk client rewrite from #159

### PR DESCRIPTION
**Pull request by jdef**
TODO:
- [x] upgrade github.com/samuel/go-zookeeper/zk package

### CODE REVIEW

**Comment by tsenart** [comment]
I don't understand what's the status here.

**Comment by jdef** [comment]
I broke this set of changes out from #159 for easier review and to allow
others to test these changes in their projects, isolated from the massive
set of changes in #159.

**Comment by tsenart** [comment]
@jdef: OK, can you update the title and description to better communicate what these changes are doing? Also, if it's reviewable please add the PTAL label, otherwise WIP.

**Comment by jdef** [comment]
closing this out, changes will be merged as part of #159

**Pull request closed without merging**
