### PR TITLE
upgrade to v0.22 bindings

### LINKED ISSUE #121: update protobuf API to v0.22+

### PR DESCRIPTION
**Pull request by jdef**
- fixes #121

### CODE REVIEW

**Comment by betawaffle** [comment]
I want this.

**Comment by jdef** [comment]
There may be some additional work to do regarding implicit vs. explicit
acknowledgements in the scheduler/executor bindings. We're very accepting
of PR's if you're so inclined :)

**Comment by jdef** [comment]
xref #102 - parameterize implicit acknowledgements

**Comment by jdef** [comment]
0.23 bindings have already been merged, closing this out

**Pull request closed without merging**
