### PR TITLE
Rename test-executor and test-framework references to example-executor and example-scheduler to be more consistent with example naming

### PR DESCRIPTION
**Pull request by chrisjs**
nit-picky but having the "test" prefix for examples always seemed a little inconsistent to me

### CODE REVIEW

**Comment by fmpwizard** [comment]
now that you are renaming this, what do you think of also renaming `example-framework` to `example-scheduler` ?

**Comment by jdef** [comment]
In the mesos/src/examples tree, the referenced java and python example schedulers and executors are actually called TestFramework/TestExecutor, and test_framework/test_executor. I imagine that this project does the same for the sake of consistency with the mesos project. But I agree that it's not very go-ish.

cc @vladimirvivien

**Comment by chrisjs** [comment]
@fmpwizard - seems reasonable, will update PR providing its agreed the name changes as a whole are acceptable

@jdef - yes I've noticed the same - yet while being consistent with the mesos project, possibly those names (test-*) are historical artifacts and the java/python ones have inherited the same naming conventions. in the end, IMO example-* seems to better describe the files then test-* and given they are examples i don't think it would be that bad to deviate in the naming for consistency. Also structs, etc inside these files are named using "example" as well

**Comment by chrisjs** [comment]
updated PR to include the suggestion from @fmpwizard to replace framework with scheduler

**Comment by fmpwizard** [comment]
Thanks for the updates @chrisjs , hopefully one of the maintainers will agree to merge this in

**Comment by chrisjs** [comment]
@vladimirvivien :+1:

**Comment by jdef** [comment]
LGTM - thanks for the PR

**Pull request merged**
